/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Subject = IDL.Record({
  'marks' : IDL.Nat,
  'remark' : IDL.Opt(IDL.Text),
  'grade' : IDL.Text,
});
export const Session = IDL.Record({
  'subjects' : IDL.Vec(Subject),
  'sessionName' : IDL.Text,
  'projectAssessment' : IDL.Opt(IDL.Text),
  'observationAssessment' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Result = IDL.Record({
  'id' : IDL.Nat,
  'studentId' : IDL.Nat,
  'finalSession' : Session,
  'overallProgress' : IDL.Text,
  'firstSession' : Session,
});
export const School = IDL.Record({
  'id' : IDL.Nat,
  'principal' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'schoolId' : IDL.Nat,
});
export const Teacher = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'schoolId' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addResult' : IDL.Func([IDL.Nat, Session, Session], [IDL.Nat], []),
  'addSchool' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addStudent' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
  'addTeacher' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteResult' : IDL.Func([IDL.Nat], [], []),
  'deleteSchool' : IDL.Func([IDL.Nat], [], []),
  'deleteStudent' : IDL.Func([IDL.Nat], [], []),
  'deleteTeacher' : IDL.Func([IDL.Nat], [], []),
  'getAllResults' : IDL.Func([], [IDL.Vec(Result)], ['query']),
  'getAllSchools' : IDL.Func([], [IDL.Vec(School)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getResult' : IDL.Func([IDL.Nat], [Result], ['query']),
  'getSchool' : IDL.Func([IDL.Nat], [School], ['query']),
  'getStudent' : IDL.Func([IDL.Nat], [Student], ['query']),
  'getTeacher' : IDL.Func([IDL.Nat], [Teacher], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateResult' : IDL.Func(
      [IDL.Nat, IDL.Nat, Session, Session, IDL.Text],
      [],
      [],
    ),
  'updateSchool' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateStudent' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  'updateTeacher' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Subject = IDL.Record({
    'marks' : IDL.Nat,
    'remark' : IDL.Opt(IDL.Text),
    'grade' : IDL.Text,
  });
  const Session = IDL.Record({
    'subjects' : IDL.Vec(Subject),
    'sessionName' : IDL.Text,
    'projectAssessment' : IDL.Opt(IDL.Text),
    'observationAssessment' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Result = IDL.Record({
    'id' : IDL.Nat,
    'studentId' : IDL.Nat,
    'finalSession' : Session,
    'overallProgress' : IDL.Text,
    'firstSession' : Session,
  });
  const School = IDL.Record({
    'id' : IDL.Nat,
    'principal' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'schoolId' : IDL.Nat,
  });
  const Teacher = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'schoolId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addResult' : IDL.Func([IDL.Nat, Session, Session], [IDL.Nat], []),
    'addSchool' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addStudent' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
    'addTeacher' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteResult' : IDL.Func([IDL.Nat], [], []),
    'deleteSchool' : IDL.Func([IDL.Nat], [], []),
    'deleteStudent' : IDL.Func([IDL.Nat], [], []),
    'deleteTeacher' : IDL.Func([IDL.Nat], [], []),
    'getAllResults' : IDL.Func([], [IDL.Vec(Result)], ['query']),
    'getAllSchools' : IDL.Func([], [IDL.Vec(School)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getResult' : IDL.Func([IDL.Nat], [Result], ['query']),
    'getSchool' : IDL.Func([IDL.Nat], [School], ['query']),
    'getStudent' : IDL.Func([IDL.Nat], [Student], ['query']),
    'getTeacher' : IDL.Func([IDL.Nat], [Teacher], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateResult' : IDL.Func(
        [IDL.Nat, IDL.Nat, Session, Session, IDL.Text],
        [],
        [],
      ),
    'updateSchool' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateStudent' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'updateTeacher' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };