/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Result {
  'id' : bigint,
  'studentId' : bigint,
  'finalSession' : Session,
  'overallProgress' : string,
  'firstSession' : Session,
}
export interface School {
  'id' : bigint,
  'principal' : string,
  'name' : string,
  'address' : string,
}
export interface Session {
  'subjects' : Array<Subject>,
  'sessionName' : string,
  'projectAssessment' : [] | [string],
  'observationAssessment' : [] | [string],
}
export interface Student { 'id' : bigint, 'name' : string, 'schoolId' : bigint }
export interface Subject {
  'marks' : bigint,
  'remark' : [] | [string],
  'grade' : string,
}
export interface Teacher {
  'id' : bigint,
  'subject' : string,
  'name' : string,
  'schoolId' : bigint,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addResult' : ActorMethod<[bigint, Session, Session], bigint>,
  'addSchool' : ActorMethod<[string, string, string], bigint>,
  'addStudent' : ActorMethod<[string, bigint], bigint>,
  'addTeacher' : ActorMethod<[string, string, bigint], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteResult' : ActorMethod<[bigint], undefined>,
  'deleteSchool' : ActorMethod<[bigint], undefined>,
  'deleteStudent' : ActorMethod<[bigint], undefined>,
  'deleteTeacher' : ActorMethod<[bigint], undefined>,
  'getAllResults' : ActorMethod<[], Array<Result>>,
  'getAllSchools' : ActorMethod<[], Array<School>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAllTeachers' : ActorMethod<[], Array<Teacher>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getResult' : ActorMethod<[bigint], Result>,
  'getSchool' : ActorMethod<[bigint], School>,
  'getStudent' : ActorMethod<[bigint], Student>,
  'getTeacher' : ActorMethod<[bigint], Teacher>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateResult' : ActorMethod<
    [bigint, bigint, Session, Session, string],
    undefined
  >,
  'updateSchool' : ActorMethod<[bigint, string, string, string], undefined>,
  'updateStudent' : ActorMethod<[bigint, string, bigint], undefined>,
  'updateTeacher' : ActorMethod<[bigint, string, string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];